apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: yytest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: registry.redhat.io/ubi9/httpd-24
        ports:
        - containerPort: 8080
