apiVersion: batch/v1
kind: Job
metadata:
  name: dig-job
  namespace: yytest
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: dig
        image: docker.io/library/busybox:latest
        command: ["sh", "-c", "sleep 30 && echo TEST21-00"]
      restartPolicy: Never
